### ISSUE TITLE
 retrieval incomplete: got only 17610303 out of 108761145 bytes

### ISSUE THREAD

**Issue by SeekPoint** [skaae/torch-gan#5]
rzai@rzai00:~/prj/torch-gan/datasets$ python create_datasets.py 
Traceback (most recent call last):
  File "create_datasets.py", line 38, in <module>
    x = create_lfw()
  File "create_datasets.py", line 27, in create_lfw
    imgs = lfw_imgs(alignment='deepfunneled', size=64, crop=50)
  File "create_datasets.py", line 16, in lfw_imgs
    imgs, names_idx, names = lfw.LFW(alignment).arrays()
  File "/home/rzai/prj/torch-gan/datasets/lfw/lfw.py", line 43, in __init__
    self._install()
  File "/home/rzai/prj/torch-gan/datasets/lfw/lfw.py", line 57, in _install
    filepath = download(url, self.data_dir)
  File "/home/rzai/prj/torch-gan/datasets/lfw/util.py", line 35, in download
    urllib.urlretrieve(url, filepath)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 284, in retrieve
    "of %i bytes" % (read, size), result)
urllib.ContentTooShortError: retrieval incomplete: got only 17610303 out of 108761145 bytes

rzai@rzai00:~/prj/torch-gan/datasets$

**Comment by SeekPoint** [comment]
miss alarm
